### ISSUE TITLE
latest windows 11 getting children: [Array]

### ISSUE THREAD

**Issue by born2net** [euberdeveloper/dree#15]
using latest windows 11 I am getting:
```children: [Array]```

is this a new issue?

node v14.17.5

thanks

S.

**Comment by euberdeveloper** [comment]
Trying with windows 10 everything seems working well to me.

Also, your issue is not very clear, it is right that `children` is an array, it is the array of all the children of the folder.

I close the issue, feel free to reopen it if you add more details
