### ISSUE TITLE
Exclude empty folder, especially when specified extensions

### ISSUE THREAD

**Issue by patarapolw** [euberdeveloper/dree#3]
This also should be a feature. I am trying to

```javascript
  dree.scan(ROOT, {
    exclude: /\.git/,
    extensions: ["md"]
  });
```

And use it for `v-treeview` (of Vue's Vuetify).

**Comment by euberdeveloper** [comment]
Soon will next version have an option "empty folders" (default true)

**Comment by euberdeveloper** [comment]
Thank you for the idea.

Now there are two options for the **scan** function:
1. `emptyDirectory`: (boolean) If true there will be the property isEmpty on the directory nodes, it will be true only if the node is a directory and is really empty, without any child, not also if its children are excluded by options
2. `excludeEmptyDirectories`: (boolan) If true all empty directories will be excluded from the result, also the ones with children but whose children are all excluded by other options such as exclude or extensions

Both the options are `false` by default.

The second option should be the one you need, you can read the doc for further information.
Please provide feedback.

**Comment by euberdeveloper** [comment]
Note: the version now is 2.0.0
