### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by abiriadev** [euberdeveloper/dree#41]
```ts
    SyntaxError: Named export 'scanAsync' not found. The requested module 
    'dree' is a CommonJS module, which may not support all module.exports as 
    named exports.
```

It would be great if `dree` could support ESM exports!

**Comment by euberdeveloper** [comment]
Hello, could I check at the code you are using? I think that it should be possible to use it in an ESM project even if CommonJS. 

It is a plan to refactor the code and build it both for ESM and CJS, but I cannot guarantee it will be done soon

**Comment by abiriadev** [comment]
@euberdeveloper Sorry, I think I used the wrong expression earlier. The library works fine in an ESM environment, but I couldn't access the named export in ESM.

> Could I see the code you are using?

[You can view the source here](https://github.com/abiriadev/dree-esm/blob/main/index.js). I'll also paste the same code for convenience:

```ts
import { scan } from 'dree'

const tree = scan('.')
console.dir(tree, { depth: null })
```

> I think it should be possible to use it in an ESM project, even if it uses CommonJS.

Yes, it works when I modify the code as follows:

```diff
- import { scan } from 'dree'
+ import dree from 'dree'

- const tree = scan('.')
+ const tree = dree.scan('.')
console.dir(tree, { depth: null })
```

The first code doesn't work, likely because `dree` uses UMD when bundling:

https://github.com/euberdeveloper/dree/blob/0685e55dfe28c5cb378d8d23ea57fe02d23cf1b9/webpack.config.js#L40

Ultimately, the choice between these syntaxes depends on personal preference, as something like tree-shaking with `dree` would be quite rare. (maybe?)

**Comment by euberdeveloper** [comment]
Release [5.0.0](https://github.com/euberdeveloper/dree/releases/tag/5.0.0) provides the module both as cjs/esm and should fix the issue.

There could be unexpected problems due to the hard refactor, please open another issue in case it happens.

I tried your code in your repo and by upgrading the version it works

**Comment by abiriadev** [comment]
It works like a charm! Thanks!!
