### ISSUE TITLE
Module not found: Default condition should be last one

### ISSUE THREAD

**Issue by AlexanderZeilmann** [euberdeveloper/dree#44]
With the current version of dree `v5.0.3` and the import
```js
import * as dree from 'dree';
```
I am getting the following warning when building my project
```
Module not found: Default condition should be last one
```

Apparently this is because some tool in my build process requires that the `default` statement is the last entry in the `exports` objects in the `package.json` file.
See for example here for a similar bug report https://github.com/vuetifyjs/vuetify/issues/17436 and stackoverflow https://stackoverflow.com/questions/76127288/module-not-found-error-default-condition-should-be-last-one

I know, this is a weird request, but can we change the the order of the exports in the `package.json` file such that `default` is listed last? That is, change
```js
// package.json
{
 // ...
  "exports": {
    ".": {
      "require": {
        "default": "./bundled/lib/commonjs/index.js",
        "types": "./bundled/lib/commonjs/index.d.ts"
      },
      "import": {
        "default": "./bundled/lib/esm/index.esm.js",
        "types": "./bundled/lib/esm/index.d.ts"
      }
    }
  },
 // ...
}
```
to
```js
// package.json
{
 // ...
  "exports": {
    ".": {
      "require": {
        "types": "./bundled/lib/commonjs/index.d.ts",
        "default": "./bundled/lib/commonjs/index.js"
      },
      "import": {
        "types": "./bundled/lib/esm/index.d.ts",
        "default": "./bundled/lib/esm/index.esm.js"
      }
    }
  },
 // ...
}
```

**Comment by euberdeveloper** [comment]
Yes, it can be done

**Comment by euberdeveloper** [comment]
From release [5.0.4](https://github.com/euberdeveloper/dree/releases/tag/5.0.4) it should work properly, thanks!
